### PR TITLE
Added open in debug option to python r2pipe

### PR DESCRIPTION
**Pull request by nomatics**

### CODE REVIEW

**Comment by radare** [comment]
This patch breaks the current order of parameters, so it will break all the scripts using the constructor with at least two parameters

**Comment by nomatics** [comment]
Fixed

**Comment by radare** [comment]
Looks good now. But i would like to think in a generic way to specify any other run flag, or even wrapping it under a class that constructs those parameters. But i didnt decided yet.

Thanks, will merge as soon as i arrive at home

**Comment by radare** [comment]
thx

**Pull request closed without merging**
