### PR TITLE
Fix Makefile install-python for macOS

### LINKED ISSUE #157: Makefile error in macOS
Hello, I've come across an issue in the `install-python` step while preparing https://github.com/Homebrew/homebrew-core/pull/12702.

```Makefile
install-python:
	test -f python/_r_core.${SOEXT}
	E=${SOEXT} ; [ `uname` = Darwin ] && E=so ; \
	echo "Installing python${PYTHON_VERSION} r2 modules in ${PYTHON_INSTALL_DIR}" ; \
	mkdir -p ${PYTHON_INSTALL_DIR} ; \
	: > ${PYTHON_INSTALL_DIR}/__init__.py ; \
	cp -rf python/r_*.py python/*.$$E ${PYTHON_INSTALL_DIR}
```
Here `E` is unconditionally set to `so` which is wrong on macOS (there. Seeing the `uname` comparison there was probably something different intended here. As a result the `cp` command can't find any `python/*.so` files and fails the build.

Is this conditional handling necessary? It seems to work fine without it.

Thank you.

### PR DESCRIPTION
**Pull request by makigumo**
fixes #157

### CODE REVIEW

**Comment by radare** [comment]
Really? Is python finally looking for .dylib instead of .so in mac? This fucks hard backward compat with old versions of python but if so we can just go forward and tell everyone to update :p

**Comment by makigumo** [comment]
I don't know if python is looking for .dylib or .so, but this patch is trying to fix that the Makefile is looking for .so files to copy when on macOS .dylib files are built. Which is breaking the build with an error message `cp: *.so: No such file or directory`.
If you are implying that the built files on macOS should not have the .dylib ending but the .so ending and thus should be renamed, then this is not a valid fix.

**Comment by radare** [comment]
yes, python on mac and windows load .so files, not .dll or .dylib files. so this pr will break the bindings

**Comment by radare** [comment]
(didnt tried yet)

**Comment by marcograss** [comment]
I tried this pull request + renaming manually .dylib to .so once installed

after those 2 steps I can import in python successfully

**Comment by radare** [comment]
Fixed in master, this patch is not correct. confirmed by @marcograss

**Pull request closed without merging**
