### PR TITLE
python3 for lang-python

### PR DESCRIPTION
**Pull request by Frefreak**
since `python-config-wrapper` seems to prevent I from using py3's python-config, currently I manually add `PYCFG=python-config` (it's 3 on my system) to the libr/lang/p/Makefile, temporally.

### CODE REVIEW

**Comment by radare** [comment]
Confirmed that it works with python2 too. thanks!

**Comment by Frefreak** [comment]
Cool! How about the python-config problem? I'm not sure in what way should the user choose between py2 or py3. Maybe replacing https://github.com/radare/radare2-bindings/blob/master/python-config-wrapper#L22-L23 with just a `break` then r2pm can honor the PYTHON_CONFIG env and use py3 correctly when user specified? No need for a lang-python3 package this way.

**Comment by radare** [comment]
Having separate packages makes it clear. But we should name it after the filename in the plugin library. This is lang_python3.so

This way it will be possible to have both installed, and each package will be installable or uninstallable at will

**Comment by radare** [comment]
So maybe we should also handle the !python2 and !python3 in the command hook. To be able to use both plugins in the same session

**Comment by Frefreak** [comment]
That would work too. Maybe I can find some time doing this in the future. Maybe for now we can just use the PYTHON_CONFIG env to handle the version (or the system default `python-config` is used).

**Comment by radare** [comment]
do you mind sending a PR for radare2-pm to add those python3 packages?

thanks!

**Comment by Frefreak** [comment]
Not at all! Will do.

**Pull request merged**
