### PR TITLE
Use Py_FinalizeEx, true/false instead of R_TRUE/R_FALSE

### PR DESCRIPTION
**Pull request by MaskRay**
https://github.com/radare/radare2/issues/3286

### CODE REVIEW

**Comment by XVilka** [comment]
@MaskRay you need to change the return type to 'bool' too then.

**Comment by XVilka** [comment]
And one more - when changing r2lang Python - please be sure to check with both Python 2 and Python 3.

**Comment by XVilka** [comment]
See also files `libr/include/r_lang.h` and `libr/lang/lang.c` in the radare2 codebase.

**Comment by MaskRay** [comment]
Compiles with Python 2 now.

I cannot change the return type to `bool` as these fields are `int`:
```c
typedef struct r_lang_plugin_t {
	const char *name;
	const char *alias;
	const char *desc;
	const char *license;
	const char **help;
	const char *ext;
	int (*init)(RLang *user);
	bool (*setup)(RLang *user);
	int (*fini)(RLang *user);
	int (*prompt)(RLang *user);
	int (*run)(RLang *user, const char *code, int len);
	int (*run_file)(RLang *user, const char *file);
	int (*set_argv)(RLang *user, int argc, char **argv);
} RLangPlugin;
```

**Comment by XVilka** [comment]
@MaskRay this why I pointed those files out, to change the type of those fields too.

**Comment by Maijin** [comment]
One should completly kill R_TRUE and R_FALSE in this repository

**Pull request merged**
